[package]
name = "extern-existential"
version = "0.1.0"
authors = ["Jethro Beekman <jethro@jbeekman.nl>"]
license = "MIT/Apache-2.0"
edition = "2018"
repository = "https://github.com/jethrogb/extern-existential"
description = "Rust extern existential types prototype"

[dependencies]
